const assert = require('assert');
const utils = require('../utils');

let content = `
Lorem Ipsum

<!--AUTO-->
DIAGRAM

DIAGRAM
<!--END-->

Lorem Ipsum
`;

let clearContent = `
Lorem Ipsum



Lorem Ipsum
`;

describe('Util tests', function () {
    describe('removeAutoGeneratedContent', function () {
        it('should remove html comments from content', function () {
            let result = utils.removeAutoGeneratedContent(content);
            assert.equal(result, clearContent);
        });
    });
});